name: CI/CD to EC2 via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./defectrak-backend
          push: true
          tags: meadnl89/starter-back:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./defectrak-frontend
          push: true
          tags: meadnl89/starter-front:latest
          build-args: |
            REACT_APP_SYNCFUSION_LICENSE=${{ secrets.REACT_APP_SYNCFUSION_LICENSE }}          

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/defectrak
            echo "Pulling ltest images from Docker Hub..."
            docker-compose pull
            echo "Restarting containers..."
            docker-compose up -d
            echo "Pruning unused resources..."
            docker system prune -af --volumes
            echo "Deployment complete!"
    
          