name: CI/CD to EC2 via Docker Hub and SSM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./defectrak-backend
          push: true
          tags: meadnl89/starter-back:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./defectrak-frontend
          push: true
          tags: meadnl89/starter-front:latest
          build-args: |
            REACT_APP_SYNCFUSION_LICENSE=${{ secrets.REACT_APP_SYNCFUSION_LICENSE }}       

      - name: Deploy via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "$INSTANCE_ID" \
            --region "$AWS_REGION" \
            --comment "Deploy latest containers" \
            --parameters commands='
              cd /home/ubuntu/defectrak &&
              docker-compose pull &&
              docker-compose up -d &&
              docker system prune -af --volumes
            ' \
            --output text